version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - evenement-network
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - evenement-network

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - evenement-network
networks:
  evenement-network:
    driver: bridge
